# Generated by Django 4.2.7 on 2023-11-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercustom',
            name='is_voter',
        ),
        migrations.AddField(
            model_name='usercustom',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='usercustom',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usercustom',
            name='family_name',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='usercustom',
            name='fathers_name',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.DeleteModel(
            name='VoterCivilian',
        ),
    ]
