# Generated by Django 4.2.7 on 2023-11-18 12:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling_system', '0002_remove_usercustom_is_voter_usercustom_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('candidates', models.ManyToManyField(blank=True, related_name='polls', to='polling_system.candidate')),
                ('voters', models.ManyToManyField(blank=True, related_name='voted_polls', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
