# Generated by Django 4.2.7 on 2023-11-19 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling_system', '0004_remove_poll_voters'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_id', models.PositiveIntegerField()),
                ('voted_candidate_id', models.PositiveIntegerField()),
                ('poll_id', models.PositiveIntegerField()),
            ],
        ),
    ]
