# Generated by Django 4.2.7 on 2023-11-19 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling_system', '0005_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='id',
        ),
        migrations.AlterField(
            model_name='vote',
            name='voter_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
