# Generated by Django 4.2.7 on 2023-11-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling_system', '0006_remove_vote_id_alter_vote_voter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='politicalparty',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
